scan_timeout = 8
add_newline = false

[line_break]
disabled = false


[directory]
read_only = " "
home_symbol = "  "
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"


[username]
show_always = true
style_root = "bold red"


[character]
success_symbol = "[ ](bold purple)"
error_symbol = "[ ](bold red)"
vicmd_symbol = "[ ](bold green)"
